services:
  backend:
    image: ghcr.io/erlang-yao/pokemon-mud-server:latest
    ports:
      - "4010:4010"

  frontend:
    image: ghcr.io/erlang-yao/pokemon-mud-client:latest
    ports:
      - "5173:80"
    depends_on:
      - backend
